@echo off
REM TCP GPS Server - Environment Configuration Script for Windows
REM Set default environment variables for development

REM Server settings
SET TCP_SERVER_HOST=localhost
SET TCP_SERVER_PORT=8181
SET TCP_MAX_CONNECTIONS=1000
SET TCP_ENABLE_TLS=false
SET TCP_CERT_FILE=cert.pem
SET TCP_KEY_FILE=key.pem

REM Performance settings
SET TCP_BUFFER_SIZE=4096
SET TCP_WORKER_COUNT=10
SET TCP_MESSAGE_QUEUE_SIZE=1000
SET TCP_HEADER_SIZE=4

REM Timeout settings
SET TCP_MAX_RETRIES=3
SET TCP_RETRY_DELAY=2s
SET TCP_READ_TIMEOUT=60s
SET TCP_WRITE_TIMEOUT=10s
SET TCP_SHUTDOWN_TIMEOUT=30s
SET TCP_IDLE_TIMEOUT=300s

REM GPS data validation
SET TCP_GPS_VALIDATION_ENABLED=true
SET TCP_MIN_LATITUDE=-90.0
SET TCP_MAX_LATITUDE=90.0
SET TCP_MIN_LONGITUDE=-180.0
SET TCP_MAX_LONGITUDE=180.0
SET TCP_LOCATION_PRECISION=6
SET TCP_MAX_TIMESTAMP_DRIFT=24h

REM Security settings
SET TCP_RATE_LIMIT_ENABLED=false
SET TCP_RATE_LIMIT_PER_MINUTE=300
SET TCP_IP_WHITELIST_ENABLED=false
SET TCP_ALLOWED_IPS=127.0.0.1

REM Logging settings
SET TCP_LOG_LEVEL=info
SET TCP_LOG_TIMESTAMPS=true
SET TCP_LOG_CLIENT_IP=true
SET TCP_LOG_GPS_COORDINATES=true
SET TCP_LOG_CONNECTION_EVENTS=true
SET TCP_LOG_MESSAGE_STATISTICS=true
SET TCP_STATISTICS_INTERVAL=60s

echo Environment variables set for TCP GPS Server
echo Run the server with: go run cmd/tcp_app/main/main.go 